In [4]:
import pandas as pd
df_2025=pd.read_csv(r'C:\Users\kumar\Desktop\KVKDEV\Aroha\KVK\2025\excel data\2025_data.csv')
df_2025.head(1)

,state,district,disease,no_of_cases,deaths,start_of_outbreak,date_of_reporting,status,action
0,Assam,Lakhimpur,Acute Diarrheal Disease,16,0,03-01-2025,03-01-2025,Under Surveillance,Cases were reported from Village Bilotia Katha...

In [5]:
df_2022=pd.read_csv(r'C:\Users\kumar\Desktop\KVKDEV\Aroha\KVK\2022\excel_data\2022_data.csv')
df_2022.head(1)

,state,district,disease,no_of_cases,deaths,start_of_outbreak,date_of_reporting,status,action
0,Jharkhand,Godda,Measles,09,0.0,05-01-22,09-01-22,Under Surveillance,"Cases reported from Village Noonajore, SC Kait..."

In [6]:
data=pd.concat([df_2025,df_2022],ignore_index=True)

In [8]:
dict_var={}
for index in range(len(data)):
    dict_var[index] = data.iloc[index].to_dict()

In [14]:
with open('data.txt', 'w+', encoding='utf-8') as mf:
    for i in dict_var:
        template = f'''
Location:State->{dict_var[i]['state']},City->{dict_var[i]['district']}
Disease:{dict_var[i]['disease']}
Occuring Date:{dict_var[i]['start_of_outbreak']}
Reporing Date:{dict_var[i]['date_of_reporting']}
Number of Cases:{dict_var[i]['no_of_cases']}
Number of Deaths:{dict_var[i]['deaths']}
Status:{dict_var[i]['status']}
Action Taken To Mitigate the Incident:
{dict_var[i]['action']}
'''
        mf.write(template)